/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Book = {
  _id: string;
  _type: "book";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  description: string;
  link?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Game = {
  _id: string;
  _type: "game";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  desc?: string;
  customeCmt?: string;
  category?: "GOAT" | "Hall of Fame" | "Pretty Good" | "Why Did I Play This";
  imge_link: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  steam_link?: string;
  website?: string;
  other_links?: Array<string>;
  pc_req?: {
    min?: {
      title?: string;
      requirements?: Array<{
        key?: string;
        value?: string;
        _type: "requirementItem";
        _key: string;
      }>;
      notes?: Array<string>;
    };
    rec?: {
      title?: string;
      requirements?: Array<{
        key?: string;
        value?: string;
        _type: "requirementItem";
        _key: string;
      }>;
      notes?: Array<string>;
    };
  };
  developer?: string;
  publisher?: string;
  genres?: Array<string>;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Bookmark = {
  _id: string;
  _type: "bookmark";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  tags?: Array<string>;
  description?: string;
  link: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  github?: string;
  demo?: string;
  type?: "website" | "app" | "library" | "other";
  status?: "live" | "building" | "completed" | "archived";
  technologies?: Array<string>;
  featured?: boolean;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  date: string;
  featured?: boolean;
  tags?: Array<string>;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Book
  | SanityImageCrop
  | SanityImageHotspot
  | Game
  | Slug
  | Bookmark
  | Project
  | Post
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries/blogs.ts
// Variable: FEATURED_BLOGS_QUERY
// Query: *[_type == "post" && defined(slug.current) && featured == true] | order(date desc) {        _id,        title,        "slug": slug.current,        description,        coverImage {            asset->{                _id,                url,                metadata {                    lqip,                    dimensions {                        width,                        height,                        aspectRatio                    }                }            },            alt,            hotspot,            crop        },        date,        featured,        tags    }
export type FEATURED_BLOGS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  date: string;
  featured: true;
  tags: Array<string> | null;
}>;

// Source: src/sanity/lib/queries/blogs.ts
// Variable: ALL_BLOGS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(date desc) {        _id,        title,        "slug": slug.current,        description,        coverImage {            asset->{                _id,                url,                metadata {                    lqip,                    dimensions {                        width,                        height,                        aspectRatio                    }                }            },            alt,            hotspot,            crop        },        date,        featured,        tags    }
export type ALL_BLOGS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  date: string;
  featured: boolean | null;
  tags: Array<string> | null;
}>;

// Source: src/sanity/lib/queries/blogs.ts
// Variable: BLOG_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {        _id,        title,        "slug": slug.current,        description,        coverImage {            asset->{                _id,                url,                metadata {                    lqip,                    dimensions {                        width,                        height,                        aspectRatio                    }                }            },            alt,            hotspot,            crop        },        date,        featured,        tags,        content    }
export type BLOG_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  date: string;
  featured: boolean | null;
  tags: Array<string> | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  > | null;
} | null;

// Source: src/sanity/lib/queries/blogs.ts
// Variable: BLOG_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(date desc) [0...20] {        "slug": slug.current    }
export type BLOG_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/sanity/lib/queries/bookmarks.ts
// Variable: ALL_BOOKMARKS_QUERY
// Query: *[_type == "bookmark"] | order(_createdAt desc) {    _id,    title,    link,    description,    tags,    _createdAt  }
export type ALL_BOOKMARKS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  link: string;
  description: string | null;
  tags: Array<string> | null;
  _createdAt: string;
}>;

// Source: src/sanity/lib/queries/projects.ts
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current) && featured == true] | order(_createdAt asc) {        _id,        title,        "slug": slug.current,        description,        image {            asset->{                _id,                url,                metadata {                    lqip,                    dimensions {                        width,                        height,                        aspectRatio                    }                }            },            alt,            hotspot,            crop        },        github,        demo,        type,        status,        technologies,        featured    }
export type FEATURED_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string;
  image: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  github: string | null;
  demo: string | null;
  type: "app" | "library" | "other" | "website" | null;
  status: "archived" | "building" | "completed" | "live" | null;
  technologies: Array<string> | null;
  featured: true;
}>;

// Source: src/sanity/lib/queries/projects.ts
// Variable: ALL_PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)] | order(_createdAt asc) {        _id,        title,        "slug": slug.current,        description,        image {            asset->{                _id,                url,                metadata {                    lqip,                    dimensions {                        width,                        height,                        aspectRatio                    }                }            },            alt,            hotspot,            crop        },        github,        demo,        type,        status,        technologies,        featured    }
export type ALL_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string;
  image: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  github: string | null;
  demo: string | null;
  type: "app" | "library" | "other" | "website" | null;
  status: "archived" | "building" | "completed" | "live" | null;
  technologies: Array<string> | null;
  featured: boolean | null;
}>;

// Source: src/sanity/lib/queries/projects.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {        _id,        title,        "slug": slug.current,        description,        image {            asset->{                _id,                url,                metadata {                    lqip,                    dimensions {                        width,                        height,                        aspectRatio                    }                }            },            alt,            hotspot,            crop        },        github,        demo,        type,        status,        technologies,        featured,        content    }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  description: string;
  image: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  github: string | null;
  demo: string | null;
  type: "app" | "library" | "other" | "website" | null;
  status: "archived" | "building" | "completed" | "live" | null;
  technologies: Array<string> | null;
  featured: boolean | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  > | null;
} | null;

// Source: src/sanity/lib/queries/projects.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)] | order(_createdAt asc) [0...20] {        "slug": slug.current    }
export type PROJECT_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/sanity/lib/queries/recommendations.ts
// Variable: ALL_GAMES_QUERY
// Query: *[_type == "game"] | order(select(category == "GOAT" => 0, category == "Hall of Fame" => 1, category == "Pretty Good" => 2, 3) asc, name asc) {    _id,    name,    "slug": slug.current,    desc,    customeCmt,    category,    imge_link {      asset->{        _id,        url,        metadata {          lqip,          dimensions {            width,            height,            aspectRatio          }        }      },      alt,      hotspot,      crop    },    steam_link,    website,    other_links,    pc_req,    developer,    publisher,    genres  }
export type ALL_GAMES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  desc: string | null;
  customeCmt: string | null;
  category:
    "GOAT" | "Hall of Fame" | "Pretty Good" | "Why Did I Play This" | null;
  imge_link: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  steam_link: string | null;
  website: string | null;
  other_links: Array<string> | null;
  pc_req: {
    min?: {
      title?: string;
      requirements?: Array<{
        key?: string;
        value?: string;
        _type: "requirementItem";
        _key: string;
      }>;
      notes?: Array<string>;
    };
    rec?: {
      title?: string;
      requirements?: Array<{
        key?: string;
        value?: string;
        _type: "requirementItem";
        _key: string;
      }>;
      notes?: Array<string>;
    };
  } | null;
  developer: string | null;
  publisher: string | null;
  genres: Array<string> | null;
}>;

// Source: src/sanity/lib/queries/recommendations.ts
// Variable: GOAT_GAMES_QUERY
// Query: *[_type == "game" && category == "GOAT"] | order(name asc) {    _id,    name,    "slug": slug.current,    desc,    customeCmt,    category,    imge_link {      asset->{        _id,        url,        metadata {          lqip,          dimensions {            width,            height,            aspectRatio          }        }      },      alt,      hotspot,      crop    },    steam_link,    website,    other_links,    pc_req,    developer,    publisher,    genres  }
export type GOAT_GAMES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  desc: string | null;
  customeCmt: string | null;
  category: "GOAT";
  imge_link: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  steam_link: string | null;
  website: string | null;
  other_links: Array<string> | null;
  pc_req: {
    min?: {
      title?: string;
      requirements?: Array<{
        key?: string;
        value?: string;
        _type: "requirementItem";
        _key: string;
      }>;
      notes?: Array<string>;
    };
    rec?: {
      title?: string;
      requirements?: Array<{
        key?: string;
        value?: string;
        _type: "requirementItem";
        _key: string;
      }>;
      notes?: Array<string>;
    };
  } | null;
  developer: string | null;
  publisher: string | null;
  genres: Array<string> | null;
}>;

// Source: src/sanity/lib/queries/recommendations.ts
// Variable: GAME_BY_SLUG_QUERY
// Query: *[_type == "game" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    desc,    customeCmt,    category,    imge_link {      asset->{        _id,        url,        metadata {          lqip,          dimensions {            width,            height,            aspectRatio          }        }      },      alt,      hotspot,      crop    },    steam_link,    website,    other_links,    pc_req,    developer,    publisher,    genres  }
export type GAME_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  desc: string | null;
  customeCmt: string | null;
  category:
    "GOAT" | "Hall of Fame" | "Pretty Good" | "Why Did I Play This" | null;
  imge_link: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  steam_link: string | null;
  website: string | null;
  other_links: Array<string> | null;
  pc_req: {
    min?: {
      title?: string;
      requirements?: Array<{
        key?: string;
        value?: string;
        _type: "requirementItem";
        _key: string;
      }>;
      notes?: Array<string>;
    };
    rec?: {
      title?: string;
      requirements?: Array<{
        key?: string;
        value?: string;
        _type: "requirementItem";
        _key: string;
      }>;
      notes?: Array<string>;
    };
  } | null;
  developer: string | null;
  publisher: string | null;
  genres: Array<string> | null;
} | null;

// Source: src/sanity/lib/queries/recommendations.ts
// Variable: GAME_SLUGS_QUERY
// Query: *[_type == "game" && defined(slug.current)] {    "slug": slug.current  }
export type GAME_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/sanity/lib/queries/recommendations.ts
// Variable: ALL_BOOKS_QUERY
// Query: *[_type == "book"] | order(_createdAt desc) {    _id,    title,    coverImage {      asset->{        _id,        url,        metadata {          lqip,          dimensions {            width,            height,            aspectRatio          }        }      },      alt,      hotspot,      crop    },    description,    link,    _createdAt  }
export type ALL_BOOKS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  description: string;
  link: string | null;
  _createdAt: string;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "post" && defined(slug.current) && featured == true] | order(date desc) {\n        _id,\n        title,\n        "slug": slug.current,\n        description,\n        coverImage {\n            asset->{\n                _id,\n                url,\n                metadata {\n                    lqip,\n                    dimensions {\n                        width,\n                        height,\n                        aspectRatio\n                    }\n                }\n            },\n            alt,\n            hotspot,\n            crop\n        },\n        date,\n        featured,\n        tags\n    }': FEATURED_BLOGS_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)] | order(date desc) {\n        _id,\n        title,\n        "slug": slug.current,\n        description,\n        coverImage {\n            asset->{\n                _id,\n                url,\n                metadata {\n                    lqip,\n                    dimensions {\n                        width,\n                        height,\n                        aspectRatio\n                    }\n                }\n            },\n            alt,\n            hotspot,\n            crop\n        },\n        date,\n        featured,\n        tags\n    }': ALL_BLOGS_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0] {\n        _id,\n        title,\n        "slug": slug.current,\n        description,\n        coverImage {\n            asset->{\n                _id,\n                url,\n                metadata {\n                    lqip,\n                    dimensions {\n                        width,\n                        height,\n                        aspectRatio\n                    }\n                }\n            },\n            alt,\n            hotspot,\n            crop\n        },\n        date,\n        featured,\n        tags,\n        content\n    }': BLOG_BY_SLUG_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)] | order(date desc) [0...20] {\n        "slug": slug.current\n    }': BLOG_SLUGS_QUERY_RESULT;
    '*[_type == "bookmark"] | order(_createdAt desc) {\n    _id,\n    title,\n    link,\n    description,\n    tags,\n    _createdAt\n  }': ALL_BOOKMARKS_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current) && featured == true] | order(_createdAt asc) {\n        _id,\n        title,\n        "slug": slug.current,\n        description,\n        image {\n            asset->{\n                _id,\n                url,\n                metadata {\n                    lqip,\n                    dimensions {\n                        width,\n                        height,\n                        aspectRatio\n                    }\n                }\n            },\n            alt,\n            hotspot,\n            crop\n        },\n        github,\n        demo,\n        type,\n        status,\n        technologies,\n        featured\n    }': FEATURED_PROJECTS_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current)] | order(_createdAt asc) {\n        _id,\n        title,\n        "slug": slug.current,\n        description,\n        image {\n            asset->{\n                _id,\n                url,\n                metadata {\n                    lqip,\n                    dimensions {\n                        width,\n                        height,\n                        aspectRatio\n                    }\n                }\n            },\n            alt,\n            hotspot,\n            crop\n        },\n        github,\n        demo,\n        type,\n        status,\n        technologies,\n        featured\n    }': ALL_PROJECTS_QUERY_RESULT;
    '*[_type == "project" && slug.current == $slug][0] {\n        _id,\n        title,\n        "slug": slug.current,\n        description,\n        image {\n            asset->{\n                _id,\n                url,\n                metadata {\n                    lqip,\n                    dimensions {\n                        width,\n                        height,\n                        aspectRatio\n                    }\n                }\n            },\n            alt,\n            hotspot,\n            crop\n        },\n        github,\n        demo,\n        type,\n        status,\n        technologies,\n        featured,\n        content\n    }': PROJECT_BY_SLUG_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current)] | order(_createdAt asc) [0...20] {\n        "slug": slug.current\n    }': PROJECT_SLUGS_QUERY_RESULT;
    '*[_type == "game"] | order(select(category == "GOAT" => 0, category == "Hall of Fame" => 1, category == "Pretty Good" => 2, 3) asc, name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    desc,\n    customeCmt,\n    category,\n    imge_link {\n      asset->{\n        _id,\n        url,\n        metadata {\n          lqip,\n          dimensions {\n            width,\n            height,\n            aspectRatio\n          }\n        }\n      },\n      alt,\n      hotspot,\n      crop\n    },\n    steam_link,\n    website,\n    other_links,\n    pc_req,\n    developer,\n    publisher,\n    genres\n  }': ALL_GAMES_QUERY_RESULT;
    '*[_type == "game" && category == "GOAT"] | order(name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    desc,\n    customeCmt,\n    category,\n    imge_link {\n      asset->{\n        _id,\n        url,\n        metadata {\n          lqip,\n          dimensions {\n            width,\n            height,\n            aspectRatio\n          }\n        }\n      },\n      alt,\n      hotspot,\n      crop\n    },\n    steam_link,\n    website,\n    other_links,\n    pc_req,\n    developer,\n    publisher,\n    genres\n  }': GOAT_GAMES_QUERY_RESULT;
    '*[_type == "game" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    desc,\n    customeCmt,\n    category,\n    imge_link {\n      asset->{\n        _id,\n        url,\n        metadata {\n          lqip,\n          dimensions {\n            width,\n            height,\n            aspectRatio\n          }\n        }\n      },\n      alt,\n      hotspot,\n      crop\n    },\n    steam_link,\n    website,\n    other_links,\n    pc_req,\n    developer,\n    publisher,\n    genres\n  }': GAME_BY_SLUG_QUERY_RESULT;
    '*[_type == "game" && defined(slug.current)] {\n    "slug": slug.current\n  }': GAME_SLUGS_QUERY_RESULT;
    '*[_type == "book"] | order(_createdAt desc) {\n    _id,\n    title,\n    coverImage {\n      asset->{\n        _id,\n        url,\n        metadata {\n          lqip,\n          dimensions {\n            width,\n            height,\n            aspectRatio\n          }\n        }\n      },\n      alt,\n      hotspot,\n      crop\n    },\n    description,\n    link,\n    _createdAt\n  }': ALL_BOOKS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface SanityQueries extends globalThis.SanityQueries {}
}
