const keywords = [
  "Aarab Nishchal",
  "Aarab",
  "Nishchal",
  "aarabii",
  "aarab",
  "caya",
  "portfolio",
  "developer",
  "web developer",
  "web development",
  "web design",
  "front-end developer",
  "full-stack developer",
  "software engineer",
  "react developer",
  "next.js",
  "nextjs developer",
  "tailwind CSS",
  "framer motion",
  "JavaScript developer",
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "open source",
  "student developer",
  "tech enthusiast",
  "personal website",
  "programming",
  "coding",
  "web applications",
  "UI/UX design",
  "responsive design",
  "modern web development",
  "tech blog",
  "coding tutorials",
  "web development tools",
  "creative coder",
  "digital portfolio",
  "developer portfolio",
  "online resume",
  "interactive web apps",
  "free web tools",
  "web innovation",
  "technology experimentation",
  "next.js app directory",
  "seo optimization",
];

export default keywords;
